name: MsgPlugin
version: '${project.version}'
main: me.nukleo.msgplugin.MsgPlugin
api-version: '1.20'
load: STARTUP
commands:
  msg:
    description: Private message a player
    usage: /<command> player message_to_send
  msgreload:
    description: Reload plugin
    usage: /<command>
    permission: msgplugin.msgreload
  reply:
    description: Reply plugin
    usage: /<command> message
    aliases:
      - r
